# Generated by Django 6.0.4 on 2026-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spam', '0002_comment_confidence_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_feedback',
        ),
        migrations.AddField(
            model_name='comment',
            name='feedback',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
